localPlanner:
  ros__parameters:
    adjacentRange: 3.0
    autonomyMode: false
    autonomySpeed: 1.0
    checkObstacle: true
    checkRotObstacle: false
    costHeightThre: 0.1
    costScore: 0.02
    dirThre: 90.0
    dirToVehicle: false
    dirWeight: 0.02
    goalClearRange: 0.5
    goalX: 0.0
    goalY: 0.0
    groundHeightThre: 0.1
    joyToCheckObstacleDelay: 5.0
    joyToSpeedDelay: 2.0
    laserVoxelSize: 0.05
    maxRelZ: 0.25
    maxSpeed: 1.0
    minPathRange: 1.0
    minPathScale: 0.5
    minRelZ: -0.5
    obstacleHeightThre: 0.3
    pathCropByGoal: true
    pathFolder: /home/lch/dog/thirdparty/autonomy_stack_go2/install/local_planner/share/local_planner/paths
    pathRangeBySpeed: true
    pathRangeStep: 0.5
    pathScale: 0.75
    pathScaleBySpeed: true
    pathScaleStep: 0.25
    pointPerPathThre: 2
    sensorOffsetX: 0.0
    sensorOffsetY: 0.0
    terrainVoxelSize: 0.2
    twoWayDrive: false
    useCost: false
    useTerrainAnalysis: false
    vehicleLength: 0.3
    vehicleWidth: 0.7
